function (prevent_root_build)
    get_filename_component(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
    get_filename_component(bindir "${CMAKE_BINARY_DIR}" REALPATH)

    if ("${srcdir}" STREQUAL "${bindir}")
        message("")
        message("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        message("DO NOT BUILD on ROOT directory")
        message("")
        message("Suggestion for you")
        message("")
        message("   mkdir build")
        message("   cd build")
        message("   cmake <options> ..")
        message("")
        message(FATAL_ERROR "stop build.")
    endif("${srcdir}" STREQUAL "${bindir}")
endfunction(prevent_root_build)

prevent_root_build()
